export const colorMap = {
    electric: "rgb(255, 180, 8)",
    water: "rgb(99, 164, 255)",
    fire: "red",
    grass: "green",
    psychic: "purple",
    ice: "cyan",
    rock: "gray",
    ground: "brown",
    flying: "skyblue",
    bug: "limegreen",
    dragon: "orange",
    dark: "black",
    fairy: "pink",
    normal: "beige",
    fighting: "maroon",
    ghost: "indigo",
    steel: "silver",
    poison: "violet",
  };